# 对空格的要求十分高

# 普通的key-value
name: warren

# 对象
Student:
  name: Warren
  age: 23

# 行内写法
Student2: {name: Warren,age: 23}

# 数组
pets:
  - cat
  - dog
  - pig

pets2: [cat,dog,pig]

# 还可以编写占位符生成随机数
person:
  name: qinjiang_${random.uuid}
  age: ${random.int(1,100)}
  happy: false
  birth: 1997/06/17
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - girl
    - music
  hello: happy
  dog:
    name: ${person.hello:other}_旺财
    age: 1


# 多环境配置
server:
  port: 8080
#选择要激活哪个环境块
spring:
  profiles:
    active: test
---
server:
  port: 8081
spring:
  profiles: dev #配置环境的名称
---
server:
  port: 8082
spring:
  profiles: test

# 开启springboot的调试类,可以知道哪些自动配置类生效，那些没有生效
debug: false
